"""empty message

Revision ID: 28174238a22c
Revises: c3e12b28065d
Create Date: 2018-07-03 05:58:35.464425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28174238a22c'
down_revision = 'c3e12b28065d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('achievement_striving', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('activity_level', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('adventurousness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('agreeableness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('altruism', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('anger', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('anxiety', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('artistic_interests', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('assertiveness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('cautiousness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('cheerfulness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('conscientiousness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('cooperation', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('depression', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('dutifulness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('emotional_range', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('emotionality', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('excitement_seeking', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('extraversion', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('friendliness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('gregariousness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('imagination', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('immoderation', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('intellect', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('liberalism', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('modesty', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('morality', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_challenge', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_closeness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_curiosity', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_excitement', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_harmony', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_ideal', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_liberty', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_love', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_practicality', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_self_expression', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_stability', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('need_structure', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('openness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('orderliness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('self_consciousness', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('self_discipline', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('self_efficacy', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('sympathy', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('trust', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('value_conservation', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('value_hedonism', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('value_openness_to_change', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('value_self_enhancement', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('value_self_transcendence', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('vulnerability', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vulnerability')
    op.drop_column('users', 'value_self_transcendence')
    op.drop_column('users', 'value_self_enhancement')
    op.drop_column('users', 'value_openness_to_change')
    op.drop_column('users', 'value_hedonism')
    op.drop_column('users', 'value_conservation')
    op.drop_column('users', 'trust')
    op.drop_column('users', 'sympathy')
    op.drop_column('users', 'self_efficacy')
    op.drop_column('users', 'self_discipline')
    op.drop_column('users', 'self_consciousness')
    op.drop_column('users', 'orderliness')
    op.drop_column('users', 'openness')
    op.drop_column('users', 'need_structure')
    op.drop_column('users', 'need_stability')
    op.drop_column('users', 'need_self_expression')
    op.drop_column('users', 'need_practicality')
    op.drop_column('users', 'need_love')
    op.drop_column('users', 'need_liberty')
    op.drop_column('users', 'need_ideal')
    op.drop_column('users', 'need_harmony')
    op.drop_column('users', 'need_excitement')
    op.drop_column('users', 'need_curiosity')
    op.drop_column('users', 'need_closeness')
    op.drop_column('users', 'need_challenge')
    op.drop_column('users', 'morality')
    op.drop_column('users', 'modesty')
    op.drop_column('users', 'liberalism')
    op.drop_column('users', 'intellect')
    op.drop_column('users', 'immoderation')
    op.drop_column('users', 'imagination')
    op.drop_column('users', 'gregariousness')
    op.drop_column('users', 'friendliness')
    op.drop_column('users', 'extraversion')
    op.drop_column('users', 'excitement_seeking')
    op.drop_column('users', 'emotionality')
    op.drop_column('users', 'emotional_range')
    op.drop_column('users', 'dutifulness')
    op.drop_column('users', 'depression')
    op.drop_column('users', 'cooperation')
    op.drop_column('users', 'conscientiousness')
    op.drop_column('users', 'cheerfulness')
    op.drop_column('users', 'cautiousness')
    op.drop_column('users', 'assertiveness')
    op.drop_column('users', 'artistic_interests')
    op.drop_column('users', 'anxiety')
    op.drop_column('users', 'anger')
    op.drop_column('users', 'altruism')
    op.drop_column('users', 'agreeableness')
    op.drop_column('users', 'adventurousness')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'achievement_striving')
    # ### end Alembic commands ###
