"""empty message

Revision ID: 6d8ddd6d8aa7
Revises: 28174238a22c
Create Date: 2018-07-03 06:45:31.391962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8ddd6d8aa7'
down_revision = '28174238a22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('info_1', sa.Boolean(), nullable=False),
    sa.Column('info_2', sa.Boolean(), nullable=False),
    sa.Column('info_3', sa.Boolean(), nullable=False),
    sa.Column('info_4', sa.Boolean(), nullable=False),
    sa.Column('info_5', sa.Boolean(), nullable=False),
    sa.Column('info_6', sa.Boolean(), nullable=False),
    sa.Column('info_7', sa.Boolean(), nullable=False),
    sa.Column('info_8', sa.Boolean(), nullable=False),
    sa.Column('info_9', sa.Boolean(), nullable=False),
    sa.Column('info_10', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statuses')
    # ### end Alembic commands ###
