"""empty message

Revision ID: bcf950a2d748
Revises: f700cc2130b1
Create Date: 2018-11-20 09:33:39.627397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf950a2d748'
down_revision = 'f700cc2130b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_userid_hash', sa.String(length=40), index=True, nullable=False),
    sa.Column('openness', sa.Float(), nullable=False),
    sa.Column('adventurousness', sa.Float(), nullable=False),
    sa.Column('artistic_interests', sa.Float(), nullable=False),
    sa.Column('emotionality', sa.Float(), nullable=False),
    sa.Column('imagination', sa.Float(), nullable=False),
    sa.Column('intellect', sa.Float(), nullable=False),
    sa.Column('liberalism', sa.Float(), nullable=False),
    sa.Column('conscientiousness', sa.Float(), nullable=False),
    sa.Column('achievement_striving', sa.Float(), nullable=False),
    sa.Column('cautiousness', sa.Float(), nullable=False),
    sa.Column('dutifulness', sa.Float(), nullable=False),
    sa.Column('orderliness', sa.Float(), nullable=False),
    sa.Column('self_discipline', sa.Float(), nullable=False),
    sa.Column('self_efficacy', sa.Float(), nullable=False),
    sa.Column('extraversion', sa.Float(), nullable=False),
    sa.Column('activity_level', sa.Float(), nullable=False),
    sa.Column('assertiveness', sa.Float(), nullable=False),
    sa.Column('cheerfulness', sa.Float(), nullable=False),
    sa.Column('excitement_seeking', sa.Float(), nullable=False),
    sa.Column('friendliness', sa.Float(), nullable=False),
    sa.Column('gregariousness', sa.Float(), nullable=False),
    sa.Column('agreeableness', sa.Float(), nullable=False),
    sa.Column('altruism', sa.Float(), nullable=False),
    sa.Column('cooperation', sa.Float(), nullable=False),
    sa.Column('modesty', sa.Float(), nullable=False),
    sa.Column('morality', sa.Float(), nullable=False),
    sa.Column('sympathy', sa.Float(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('emotional_range', sa.Float(), nullable=False),
    sa.Column('anger', sa.Float(), nullable=False),
    sa.Column('anxiety', sa.Float(), nullable=False),
    sa.Column('depression', sa.Float(), nullable=False),
    sa.Column('immoderation', sa.Float(), nullable=False),
    sa.Column('self_consciousness', sa.Float(), nullable=False),
    sa.Column('vulnerability', sa.Float(), nullable=False),
    sa.Column('need_challenge', sa.Float(), nullable=False),
    sa.Column('need_closeness', sa.Float(), nullable=False),
    sa.Column('need_curiosity', sa.Float(), nullable=False),
    sa.Column('need_excitement', sa.Float(), nullable=False),
    sa.Column('need_harmony', sa.Float(), nullable=False),
    sa.Column('need_ideal', sa.Float(), nullable=False),
    sa.Column('need_liberty', sa.Float(), nullable=False),
    sa.Column('need_love', sa.Float(), nullable=False),
    sa.Column('need_practicality', sa.Float(), nullable=False),
    sa.Column('need_self_expression', sa.Float(), nullable=False),
    sa.Column('need_stability', sa.Float(), nullable=False),
    sa.Column('need_structure', sa.Float(), nullable=False),
    sa.Column('value_conservation', sa.Float(), nullable=False),
    sa.Column('value_openness_to_change', sa.Float(), nullable=False),
    sa.Column('value_hedonism', sa.Float(), nullable=False),
    sa.Column('value_self_enhancement', sa.Float(), nullable=False),
    sa.Column('value_self_transcendence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_twitter_userid_hash'), 'users', ['twitter_userid_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_twitter_userid_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
