"""empty message

Revision ID: c3e12b28065d
Revises: 1501cfaffe84
Create Date: 2018-06-30 06:47:10.709590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3e12b28065d'
down_revision = '1501cfaffe84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_userid', sa.String(length=255), nullable=False))
    op.drop_column('users', 'twitter_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_user_id', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'twitter_userid')
    # ### end Alembic commands ###
